env:
  es6: true
  browser: true
  webextensions: true
extends: '@cnwangjie/eslint-config'
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: 0
globals:
  DEBUG: true
  PRODUCTION: true
  MOZ: true
  ga: true
